defaults:
  -
    scope:
      path: "notes" 
    values:
      layout: "note"
      author: "Maxime Tournier"


markdown: kramdown
highlighter: pygments

kramdown:
  syntax_highlighter: pygments
  input: GFM



